---
kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: amd64

steps:
#- name: restore-cache
#  image: drillster/drone-volume-cache
#  restore: true
#  mount:
#  - ./node_modules
#  volumes:
#  - /var/local/drone-cache:/cache

- name: build
  image: node
  commands:
  - npm install
  - npm run build
  when:
    event:
    - pull_request

#- name: rebuild-cache
#  image: drillster/drone-volume-cache
#  rebuild: true
#  mount:
#  - ./node_modules
#  volumes:
#  - /var/local/drone-cache:/cache

- name: deployment-to-oss
  image: trylife/aliyun-ossutil:latest
  environment:
    OSS_KEY_ID: LTAI4GHxcTAfq3GFTiKBRSEV
#      from_secret: OSS_KEY_ID
    OSS_KEY_SECRET: kHreImOpBGxhoximyV2CzEU5ry7BOM
#      from_secret: OSS_KEY_SECRET
    TEST:
      from_secret: OSS_KEY_ID
  settings:
    TEST_TEST:
      from_secret: OSS_KEY_SECRET
  commands:
#    - echo $TEST
#    - echo $TEST_TEST
    - ossutil config  -L CH -e "oss-cn-beijing.aliyuncs.com" -i $TEST -k $OSS_KEY_SECRET
    - ossutil cp -rf ./dist oss://sy-ui/yuzeng/huawei-cce/test/external
  when:
    event:
    - pull_request

node:
  instance: agent-amd64
