---
kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: amd64

steps:
#- name: restore-cache
#  image: drillster/drone-volume-cache
#  restore: true
#  mount:
#  - ./node_modules
#  volumes:
#  - /var/local/drone-cache:/cache

- name: build
  image: node
  commands:
  - npm install
  - npm run build
  when:
    event:
    - pull_request

#- name: rebuild-cache
#  image: drillster/drone-volume-cache
#  rebuild: true
#  mount:
#  - ./node_modules
#  volumes:
#  - /var/local/drone-cache:/cache

#- name: deployment-to-oss
#  image: trylife/aliyun-ossutil:latest
#  secrets: [oss_key_id, oss_key_secret]
#  commands:
#    - ossutil config  -L CH -e "oss-cn-beijing.aliyuncs.com" -i $${OSS_KEY_ID} -k $${OSS_KEY_SECRET}
#    - pwd
#    - ossutil cp -rf ./dist oss://sy-ui/yuzeng/huawei-cce/${DRONE_COMMIT_BRANCH}/${DRONE_BUILD_NUMBER}/external
#  when:
#    event:
#    - pull_request

node:
  instance: agent-amd64
